FROM python:3.11-slim

RUN adduser --disabled-password --gecos '' webuser
RUN mkdir -p /app/flask_session && chown webuser:webuser /app/flask_session

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

USER webuser

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5050", "web.app:app"]