services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      TZ: Europe/Moscow
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      db:
        condition: service_healthy
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
      ERROR_CHAT_ID: ${ERROR_CHAT_ID}
      LOG_LEVEL: ${LOG_LEVEL}
    restart: on-failure
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5050:5050"
    environment:
      FLASK_SECRET: ${FLASK_SECRET}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      REDIS_URL: ${REDIS_URL}

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: ${REDIS_URL}

volumes:
  pgdata:
