FROM python:3.11-slim

RUN adduser --disabled-password --gecos '' celeryuser

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

USER celeryuser

CMD ["celery", "-A", "celery_app", "worker", "--loglevel=info"]