FROM python:3.11-slim

# Установка зависимостей
RUN pip install --no-cache-dir -U pip setuptools wheel && \
    useradd -m botuser && \
    mkdir -p /app/logs /app/celery_data && \
    chown -R botuser:botuser /app

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

USER botuser

CMD ["python", "-m", "bot.main"]